import { Container} from "react-bootstrap"

const Whitepaper = () =>{
  return (
    <main className="pt-4">
      <Container className="border-lemon rounded-4 py-2">
      <p className=" fs-4 text-uppercase text-lemon font-supadao">Whitepaper</p>
      <p className=" fs-5 text-uppercase font-supadao">SupaDAO: A Decentralized Exchange on the
Monad Blockchain</p>
      <p className="fw-bold h6 py-3">Abstract</p>
      <p>SupaDAO is an innovative decentralized exchange
(DEX) designed to revolutionize the DeFi landscape
on the Monad blockchain. Our platform enables
seamless liquidity provision, efficient token swaps,
and robust governance participation for liquidity
providers. By leveraging the unique capabilities of
Monad, SupaDAO aims to deliver unparalleled
performance, security, and user experience in the
decentralized finance (DeFi) ecosystem.</p>

        <p className="fw-bold text-uppercase fs-5 text-lemon py-3">Introduction</p>
        <p className="fw-bold text-capitalize fs-6   py-1">background</p> 
        <p>
       The DeFi ecosystem has witnessed exponential
growth, driven by the demand for decentralized
financial services that eliminate intermediaries,
reduce costs, and increase transparency. Central to
this ecosystem are decentralized exchanges
(DEXs), which facilitate peer-to-peer trading of
cryptocurrencies. However, existing DEXs face
challenges such as high transaction fees, slow
confirmation times, and governance inefficiencies.
 
        </p>
        
       <p className="fw-bold text-capitalize fs-6 py-1">The monad blockchain</p>  
       <p>
       Monad is a next-generation blockchain designed to
address the limitations of current blockchain
architectures. It offers enhanced scalability, faster
transaction processing, and reduced costs, making
it an ideal platform for DeFi applications.

       </p>
       
       <p className="fw-bold text-capitalize fs-5 py-3">SupaDao overview</p>
       <p>
       SupaDAO is a DEX built on the Monad blockchain,
aiming to provide a seamless and efficient trading
experience while empowering users through
decentralized governance. Our platform offers:

       </p>
       <ol>
        <li><span className="fw-bold">Liquidity Provision: </span>Users can provide liquidity to
various trading pairs, earning fees and rewards in
return.</li>
<li><span className="fw-bold">Token swap: </span>Fast and efficient token swaps with
minimal slippage and competitive fees.</li>
<li><span className="fw-bold">Governance: </span>Liquidity providers can participate
in the governance of the protocol, influencing key
decisions and future developments.</li>
       </ol>
       
       <p className="fw-bold text-uppercase fs-5 text-lemon py-3">Key features</p>
       <ol>
        <li>
        <p className="fw-bold py-2">Liquidity Provision</p>
        <p>SupaDAO enables users to provide liquidity to
trading pairs by depositing their tokens into
liquidity pools. In return, liquidity providers (LPs)
earn a share of the trading fees generated by the
pool. Additionally, LPs receive SupaDAO
governance tokens, granting them a stake in the
protocol's governance.
</p>
         <p className="fw-bold">Benefits for Liquidity Providers</p>
         <ul>
          <li><span className="fw-bold">Earn Fees: </span>LPs earn a portion of the transaction
fees proportional to their share in the liquidity
pool.</li>

          <li><span className="fw-bold">Incentives: </span>LPs receive SupaDAO governance
tokens as incentives for providing liquidity</li>
          <li><span className="fw-bold">Flexible Withdrawal: </span>LPs can withdraw their
tokens at any time, along with their earned fees
and incentives.</li>
         </ul>
        </li>
        
       <li>
        <p className="fw-bold py-2">Token swap</p>
        <p>SupaDAO facilitates fast and efficient token swaps
with minimal slippage and low fees. Users can
exchange tokens directly from their wallets
without the need for intermediaries. Our DEX
leverages the scalability and speed of the Monad
blockchain to offer a superior trading experience.
</p>
         <p className="fw-bold">Advantages of SupaDAO Token Swap</p>
         <ul>
          <li><span className="fw-bold">Low Fees: </span>Leveraging Monad's low-cost
infrastructure, SupaDAO offers competitive
transaction fees.</li>

          <li><span className="fw-bold">High Speed: </span>Fast transaction processing
ensures quick swaps, enhancing user
experience.</li>
          <li><span className="fw-bold">Secure Trading: </span>Decentralized architecture
ensures that users retain control of their funds
at all times.</li>
         </ul>
        </li> 
        
       <li>
        <p className="fw-bold py-2">Governance</p>
        <p>SupaDAO is committed to decentralized
governance, allowing liquidity providers to
participate in the decision-making process.
Governance tokens grant voting rights, enabling
LPs to propose and vote on key protocol changes,
new features, and upgrades.
</p>
         <p className="fw-bold">Governance Mechanism</p>
         <ul>
          <li><span className="fw-bold">Propsal Submission: </span>Governance token
holders can submit proposals for protocol
changes or new features.
</li>

          <li><span className="fw-bold">Voting Process: </span>All token holders can vote on
proposals. Votes are weighted based on the
number of tokens held.</li>
          <li><span className="fw-bold">Implementation: </span>Approved proposals are
implemented by the development team,
ensuring community-driven development.
</li>
          </ul>
        </li> 
       </ol>
       
       
      </Container>
    </main>
  )
}

export default Whitepaper